name = "baytides-form-handler"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "https://baytides.org"
TO_EMAIL = "admin@baytides.org"

# Custom domain - Cloudflare will automatically set up DNS
[[routes]]
pattern = "forms.baytides.org"
custom_domain = true
